version: '3'

networks:
  backend:
    driver: bridge

services:

### Phoenix ###########################################
    phoenix1.4:
      build: ./phoenix1.4
      volumes:
        - ${APP_CODE_PATH_HOST}:/app
      ports:
        - "${PHOENIX_PORT}:4000"
        - "${WEBPACK_DEVSERVER_PORT}:8080"

### PostgreSQL ###########################################
    postgres:
      build: ./postgres
      volumes:
        - ${DATA_PATH_HOST}/${COMPOSE_PROJECT_NAME}/postgres:/var/lib/postgresql/data
      ports:
        - "${POSTGRES_PORT}:5432"
      environment:
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      networks:
        - backend

### Ridgepole ################################################
    ridgepole:
      build: ./ridgepole
      volumes:
        - ${RIDGEPOLE_CONFIG_PATH}:/ridgepole
      networks:
        - backend

### ChromeDriver ################################################
    chromedriver:
      image: yukinying/chrome-headless-browser-selenium
      networks:
        - backend
      cap_add:
        - SYS_ADMIN
      ports:
        - ${SELENIUM_PORT}:4444
