version: '3'

networks:
  backend:
    driver: bridge

services:

### Phoenix ###########################################
    phoenix:
      build: ./elixir
      volumes:
        - ${APP_CODE_PATH_HOST}:/app
      ports:
        - "${PHOENIX_PORT}:4000"
        - "${WEBPACK_DEVSERVER_PORT}:8080"

### PostgreSQL ###########################################
    postgres:
      build: ./postgres
      volumes:
        - ${DATA_PATH_HOST}/postgres:/var/lib/postgresql/data
      ports:
        - "${POSTGRES_PORT}:5432"
      environment:
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      networks:
        - backend

### Ridgepole ################################################
    ridgepole:
      build: ./ridgepole
      volumes:
        - ${RIDGEPOLE_CONFIG_PATH}:/ridgepole
      networks:
        - backend
